version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.0
    - 2.3.1
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: lodash
    versions:
    - 4.17.20
